name: 'Build Artifact'

description: 'Builds the plugin artifact'
inputs:
  version-number:
    description: 'The version number to use for the build'
    required: true
    default: '0.0.0'

runs:
  using: "composite"
  steps:
    - uses: microsoft/setup-msbuild@v2

    - name: create output directory
      shell: pwsh
      run: |
        mkdir ./out/
        mkdir ./dist/

    - name: restore sln
      shell: pwsh
      run: |
        msbuild -t:restore GoogleDriveSync.sln

    - name: publish-windows
      uses: ./.github/actions/build-single-platform
      with:
        version-number: ${inputs.version-number}
        keepass-location: ../lib/bin/KeePass-windows.exe
        output-name: win

    - name: publish-linux
      uses: ./.github/actions/build-single-platform
      with:
        version-number: ${inputs.version-number}
        keepass-location: ../lib/bin/KeePass-2.47-ubuntu.exe
        output-name: linux