name: Create pre-release on PR

on: pull_request


jobs:
  create-prerelease:
    runs-on: windows-latest
    permissions: 
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
  
    - name: build artifacts
      uses: ./.github/actions/build-artifact
      with:
        GCPCLIENTID: ${{vars.GCPCLIENTID}}
        GDRIVEAPPID: ${{vars.GDRIVEAPPID}}
        GDRIVEFILEPICKERAPIKEY: ${{vars.GDRIVEFILEPICKERAPIKEY}}
        PublicClientSecret: ${{vars.PublicClientSecret}}
        UpdateUrlPubKey: ${{vars.UpdateUrlPubKey}}


    - name: List files in dist directory
      # This step is to verify that the files are created correctly
      shell: pwsh
      run: |
        [System.IO.FileSystemInfo[]]$files = Get-ChildItem ./dist/
        Write-Host "$($files.Count) files found in dist directory:"
        $files

    - name: Upload zipped Artifacts
      uses: actions/upload-artifact@v4
      id: zip-upload
      with:
        name: zip-artifact
        retention-days: 15
        path: ./dist/**.zip
        if-no-files-found: error

    - uses: actions/github-script@v6
      env:
        PR_NUMBER: ${{ github.event.number }}
        PR_NOTES: |
          Build artifacts (expire in 15 days):
          | Name | Link |
          |------|------|
          | zip | ${{ steps.zip-upload.outputs.artifact-url }} |
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: process.env.PR_NUMBER,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.PR_NOTES
          })