name: Publish artifacts on release

on:
  release: 
    types: 
      - published

jobs:
  build-and-publish:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
    - uses: actions/checkout@v3
  
    - name: build artifacts
      uses: ./.github/actions/build-artifact
      with:
        version-number: ${{ github.event.release.name }}
        GCPCLIENTID: ${{vars.GCPCLIENTID}}
        GDRIVEAPPID: ${{vars.GDRIVEAPPID}}
        GDRIVEFILEPICKERAPIKEY: ${{vars.GDRIVEFILEPICKERAPIKEY}}
        PublicClientSecret: ${{vars.PublicClientSecret}}
        UpdateUrlPubKey: ${{vars.UpdateUrlPubKey}}


    - name: List files in dist directory
      # This step is to verify that the files are created correctly
      shell: pwsh
      run: |
        [System.IO.FileSystemInfo[]]$files = Get-ChildItem ./dist/
        Write-Host "$($files.Count) files found in dist directory:"
        $files

    - name: Generate AutoUpdate file
      run: |
        "${{secrets.SIGNING_PRIVATEKEY_XML}}" | Set-Content .\lib\src\GenVerInfo\privateKey.xml -Force
        msbuild -t:publish -p:Configuration=Release .\lib\src\GenVerInfo\GenVerInfo.csproj
        & ".\lib\src\GenVerInfo\bin\Release\net48\GenVerInfo.exe" "./src/bin/Any Cpu/Release/net48/publish/KPSyncForDrive.dll" ./dist/kpsync_final.txt

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: './dist/*'

    - uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs').promises;

          const files = await fs.readdir('./dist');
          for (const file of files) {
            await github.rest.repos.uploadReleaseAsset({
              name: file,
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ github.event.release.id }},
              data: await fs.readFile(`./dist/${file}`)
            });
          }
